CREATE TABLE if not exists order_schema.orders (
                               shipping_fee double precision NULL,
                               subtotal double precision NULL,
                               total_amount double precision NULL,
                               created_at timestamp(6) with time zone NOT NULL,
                               id bigint NOT NULL,
                               order_date timestamp(6) with time zone NULL,
                               updated_at timestamp(6) with time zone NULL,
                               user_id bigint NULL,
                               order_status character varying(255) NULL,
                               payment_method character varying(255) NULL,
                               payment_status character varying(255) NULL,
                               shipping_address character varying(255) NULL,
                               tracking_number character varying(255) NULL,
                               transaction_id character varying(255) NULL
);

ALTER TABLE if exists order_schema.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);

CREATE TABLE if not exists order_schema.order_item (
                                   quantity integer NULL,
                                   unit_price double precision NULL,
                                   id bigint NOT NULL,
                                   order_id bigint NULL,
                                   product_id bigint NULL,
                                   item_img character varying(255) NULL,
                                   item_name character varying(255) NULL
);

ALTER TABLE if exists order_schema.order_item
    ADD CONSTRAINT order_item_pkey PRIMARY KEY (id);

CREATE TABLE if not exists order_schema.outbox_events (
                                      retry_count integer NOT NULL,
                                      created_at timestamp(6) without time zone NULL,
                                      id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                      aggregate_id character varying(255) NULL,
                                      event_type character varying(255) NULL,
                                      payload text NULL,
                                      source_system character varying(255) NULL,
                                      status character varying(255) NULL,
                                      topic character varying(255) NULL
);

ALTER TABLE if exists order_schema.outbox_events
    ADD CONSTRAINT outbox_events_pkey PRIMARY KEY (id);

CREATE TABLE order_schema.shedlock (
                                         name character varying(64) NOT NULL,
                                         lock_until timestamp without time zone NOT NULL,
                                         locked_at timestamp without time zone NOT NULL,
                                         locked_by character varying(255) NOT NULL
);

ALTER TABLE order_schema.shedlock
    ADD CONSTRAINT shedlock_pkey PRIMARY KEY (name);