CREATE TABLE IF NOT EXISTS user_schema.users (
                              is_active boolean NULL,
                              is_locked boolean NULL,
                              is_logged_in boolean NULL,
                              latitude double precision NULL,
                              longitude double precision NULL,
                              wrong_attempts integer NULL,
                              first_login_time timestamp(6) without time zone NULL,
                              id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              last_login_time timestamp(6) without time zone NULL,
                              locked_date_time timestamp(6) without time zone NULL,
                              email character varying(255) NOT NULL,
                              login_name character varying(255) NULL,
                              password character varying(255) NULL,
                              profile_img character varying(255) NULL,
                              roles character varying(255) [] NULL,
                              last_name character varying(255) NULL,
                              contact character varying(255) NULL,
                              first_name character varying(255) NULL
);

ALTER TABLE IF EXISTS user_schema.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS user_schema.roles (
                              id bigint NOT NULL,
                              name character varying(255) NULL
);

ALTER TABLE IF EXISTS  user_schema.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS user_schema.address (
                                id bigint NOT NULL,
                                user_id bigint NULL,
                                address_line1 character varying(255) NULL,
                                address_line2 character varying(255) NULL,
                                city character varying(255) NULL,
                                country character varying(255) NULL,
                                state character varying(255) NULL,
                                zip_code character varying(255) NULL
);

ALTER TABLE IF EXISTS user_schema.address
    ADD CONSTRAINT address_pkey PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS user_schema.users_outbox_events (
                                            id uuid NOT NULL,
                                            aggregate_id character varying(255) NULL,
                                            created_at timestamp(6) without time zone NULL,
                                            event_type character varying(255) NULL,
                                            payload text NULL,
                                            retry_count integer NOT NULL,
                                            target_system character varying(255) NULL,
                                            status character varying(255) NULL,
                                            topic character varying(255) NULL
);

ALTER TABLE IF EXISTS user_schema.users_outbox_events
    ADD CONSTRAINT users_outbox_events_pkey PRIMARY KEY (id);

CREATE TABLE user_schema.shedlock (
                                 name character varying(64) NOT NULL,
                                 lock_until timestamp without time zone NOT NULL,
                                 locked_at timestamp without time zone NOT NULL,
                                 locked_by character varying(255) NOT NULL
);

ALTER TABLE user_schema.shedlock
    ADD CONSTRAINT shedlock_pkey PRIMARY KEY (name);

CREATE SEQUENCE IF NOT EXISTS user_schema.token_verification_seq
    START WITH 1
    INCREMENT BY 50;

CREATE TABLE IF NOT EXISTS user_schema.token_verification (
                                                   id bigint NOT NULL,
                                                   token character varying(255) NULL,
                                                   user_id bigint NULL,
                                                   attempt_count int NULL,
                                                   is_verified boolean NULL,
                                                   expiry_date timestamp(6) without time zone NULL,
                                                   updated_at timestamp(6) without time zone NULL,
                                                   created_at timestamp(6) without time zone NULL
);

ALTER TABLE IF EXISTS user_schema.token_verification
    ADD CONSTRAINT token_verification_pkey PRIMARY KEY (id);