CREATE TABLE IF NOT EXISTS product_schema.products (
  categoryid integer NULL,
  price double precision NULL,
  stock_quantity integer NULL,
  id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  name character varying(255) NULL,
  url character varying(255) NULL
);

ALTER TABLE IF EXISTS  product_schema.products
ADD CONSTRAINT products_pkey PRIMARY KEY (id);

CREATE TABLE IF NOT EXISTS product_schema.categories (
    is_active boolean NOT NULL,
    category_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone NULL,
    name character varying(255) NULL,
    slug character varying(255) NULL
);

ALTER TABLE IF EXISTS  product_schema.categories
ADD CONSTRAINT categories_pkey PRIMARY KEY (category_id);

CREATE TABLE product_schema.shedlock (
                                      name character varying(64) NOT NULL,
                                      lock_until timestamp without time zone NOT NULL,
                                      locked_at timestamp without time zone NOT NULL,
                                      locked_by character varying(255) NOT NULL
);

ALTER TABLE product_schema.shedlock
    ADD CONSTRAINT shedlock_pkey PRIMARY KEY (name);