server:
      port: 8090
spring:
      application:
            name: cart
      profiles:
            active: "prod"
      redis:
            host: localhost # Or your Redis host
            port: 6379

management:
      endpoints:
            web:
                  exposure:
                        include: health